# Generated by Django 5.0.7 on 2024-07-20 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoryColor', models.IntegerField()),
                ('categoryTitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('isFinished', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.category')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendarId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendarDate', models.DateField()),
                ('themeId', models.UUIDField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.post')),
            ],
        ),
    ]
