# Generated by Django 5.0.7 on 2024-07-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_calendar_post_post_calendar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='calendar',
        ),
        migrations.AddField(
            model_name='calendar',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.post'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryTitle',
            field=models.CharField(max_length=255),
        ),
    ]
