# Generated by Django 5.0.7 on 2024-07-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_post_calendar_calendar_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.post'),
        ),
    ]
