# Generated by Django 5.0.7 on 2024-07-24 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remove_calendar_post_post_calendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreenSetting',
            fields=[
                ('settingId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_visible_not_yet_task', models.BooleanField(default=True)),
                ('is_visible_today_task', models.BooleanField(default=True)),
                ('is_visible_some_task', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScreenTheme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
            ],
        ),
    ]
