# Generated by Django 5.0.7 on 2024-07-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_homescreensetting_screensetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryColor',
            field=models.CharField(max_length=255),
        ),
    ]
