# Generated by Django 5.0.7 on 2024-07-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryColor',
            field=models.CharField(max_length=7),
        ),
    ]
