# Generated by Django 5.0.7 on 2024-07-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_theme_is_use_alter_category_categorycolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryColor',
            field=models.IntegerField(),
        ),
    ]
