# Generated by Django 5.0.7 on 2024-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_alter_category_categorycolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
